apiVersion: v1
kind: Service
metadata:
  name: ci-cd-app
  labels:
    app: ci-cd-app
spec:
  type: ClusterIP
  selector:
    app: ci-cd-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
